packages:
  - apps/*
  - packages/**

catalog:
  viem: 2.44.1
  wagmi: 2.14.11
  swr: ^2.2.5
  react: ^18.2.0
  react-dom: ^18.2.0
  "@types/react": 18.x
  "@noble/hashes": ^2.0.1
  zustand: ^4.5.7
  typescript: ^5.9.2
  vitest: ^4.0.18
  rimraf: ^6.0.1
  "@aztec/aztec.js": ^4.1.0-rc.4
  starknet: ^8.0.0
  "@coral-xyz/anchor": ^0.30.1
  "@solana/spl-token": ^0.4.14
  "@solana/web3.js": ^1.98.4
  "@ton/ton": ^13.11.1
  "@ton/core": ^0.53.0
  "@ton/crypto": ^3.2.0
  fuels: ^0.101.3